/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooBgdPdf2.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooBgdPdf2) 

 RooBgdPdf2::RooBgdPdf2(const char *name, const char *title, 
                        RooAbsReal& _mt,
                        RooAbsReal& _bb,
                        RooAbsReal& _cc,
                        RooAbsReal& _dd) :
   RooAbsPdf(name,title), 
   mt("mt","mt",this,_mt),
   bb("bb","bb",this,_bb),
   cc("cc","cc",this,_cc),
   dd("dd","dd",this,_dd)
 { 
 } 


 RooBgdPdf2::RooBgdPdf2(const RooBgdPdf2& other, const char* name) :  
   RooAbsPdf(other,name), 
   mt("mt",this,other.mt),
   bb("bb",this,other.bb),
   cc("cc",this,other.cc),
   dd("dd",this,other.dd)
 { 
 } 



 Double_t RooBgdPdf2::evaluate() const 
 { 
   Double_t tmp = mt*mt + bb*mt + cc;
   Double_t tmp2 = pow(tmp, dd);
   if(tmp2 <= 0)
     return 0;
   return 1./tmp2;

 } 



