/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooBgdPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooBgdPdf) 

 RooBgdPdf::RooBgdPdf(const char *name, const char *title, 
                        RooAbsReal& _mt,
                        RooAbsReal& _bb,
                        RooAbsReal& _cc) :
   RooAbsPdf(name,title), 
   mt("mt","mt",this,_mt),
   bb("bb","bb",this,_bb),
   cc("cc","cc",this,_cc)
 { 
 } 


 RooBgdPdf::RooBgdPdf(const RooBgdPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   mt("mt",this,other.mt),
   bb("bb",this,other.bb),
   cc("cc",this,other.cc)
 { 
 } 



 Double_t RooBgdPdf::evaluate() const 
 { 
   if (mt == -bb)
     return 0;
   Double_t tmp = pow(mt+bb, cc);
   return 1./tmp;
 } 



