/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBGDPDF2
#define ROOBGDPDF2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBgdPdf2 : public RooAbsPdf {
public:
  RooBgdPdf2() {} ; 
  RooBgdPdf2(const char *name, const char *title,
	      RooAbsReal& _mt,
	      RooAbsReal& _bb,
	      RooAbsReal& _cc,
	      RooAbsReal& _dd);
  RooBgdPdf2(const RooBgdPdf2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBgdPdf2(*this,newname); }
  inline virtual ~RooBgdPdf2() { }

protected:

  RooRealProxy mt ;
  RooRealProxy bb ;
  RooRealProxy cc ;
  RooRealProxy dd ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBgdPdf2,1) // Your description goes here...
};
 
#endif
