/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOBGDPDF
#define ROOBGDPDF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooBgdPdf : public RooAbsPdf {
public:
  RooBgdPdf() {} ; 
  RooBgdPdf(const char *name, const char *title,
	      RooAbsReal& _mt,
	      RooAbsReal& _bb,
	      RooAbsReal& _cc);
  RooBgdPdf(const RooBgdPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooBgdPdf(*this,newname); }
  inline virtual ~RooBgdPdf() { }

protected:

  RooRealProxy mt ;
  RooRealProxy bb ;
  RooRealProxy cc ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooBgdPdf,1) // Your description goes here...
};
 
#endif
